#!/usr/bin/python3


__version__ = '18.12.2022'
__author__ = 'Serhiy Kobyakov'


import wx
from emcalc import str_is_float
from emcalc import nm_to_cm
from emcalc import nm_to_ev
from emcalc import cm_to_nm
from emcalc import cm_to_ev
from emcalc import ev_to_nm
from emcalc import ev_to_cm
from emcalc import nm_to_range


class FloatTextCtrl(wx.TextCtrl):
    # TextCtrl which accepts valid floats only (simple numbers, no scientific notation)
    # you can safely make floats from the string without risk to crash the application
    def __init__(self, parent, id=wx.ID_ANY, value="", pos=wx.DefaultPosition, size=wx.DefaultSize, style=0,
                 validator=wx.DefaultValidator, name=wx.TextCtrlNameStr):
        wx.TextCtrl.__init__(self, parent=parent, id=id, value=value, size=size, style=style)
        self.Bind(wx.EVT_KEY_DOWN, lambda event: self.catch_comma(event))
        self.Bind(wx.EVT_CHAR, lambda event: self.filter_num_and_control(event))

    def catch_comma(self, event):
        # substitute dot for comma so there would be no problems with calculations later
        key_code = event.GetKeyCode()

        if key_code == ord(','):
            if '.' not in self.GetLineText(0):
                keyinput = wx.UIActionSimulator()
                keyinput.Char(ord('.'))
        else:
            event.Skip()

    def filter_num_and_control(self, event):
        # filter out inputs which are not numeric or widget controls
        key_raw_value = self.GetValue().strip()
        key_code = event.GetKeyCode()
        # print(f'raw: {key_raw_value}, key code: {key_code}, char: {chr(key_code)}')
        if 0 <= key_code <= 7:
            pass
        elif 8 <= key_code <= 9:
            event.Skip()
        elif 10 <= key_code <= 26:
            pass
        elif key_code == 27:  # ESC
            event.Skip()
        elif 28 <= key_code <= 45:
            pass
        elif key_code == 46:  # .
            if '.' not in key_raw_value:
                event.Skip()
        elif key_code == 47:  # /
            pass
        elif 48 <= key_code <= 57:  # 0..9
            if str_is_float(key_raw_value + chr(key_code)):
                if float(key_raw_value + chr(key_code)) >= 0:
                    self.SetModified(True)
                    event.Skip()
        elif 58 <= key_code <= 126:
            pass
        elif key_code == 127:  # DEL
            event.Skip()
        elif 128 <= key_code <= 255:
            pass
        else:
            event.Skip()


class LcalcFrame(wx.Frame):
    def __init__(self, parent, title):
        super().__init__(parent, title=title, style=wx.DEFAULT_FRAME_STYLE ^ wx.RESIZE_BORDER)

        # set the application icon
        icon = wx.Icon()
        icon.CopyFromBitmap(wx.Bitmap("emcalc.ico", wx.BITMAP_TYPE_ANY))
        self.SetIcon(icon)

        # make the main panel and increase system font 2 times for it
        self.the_panel = wx.Panel(self, wx.ID_ANY)
        systemfont = wx.SystemSettings.GetFont(wx.SYS_DEFAULT_GUI_FONT)
        self.the_panel.SetFont(systemfont.Scale(2))

        # create statusbar
        self.status_bar = self.CreateStatusBar(1)

        labelcm = wx.StaticText(self.the_panel, id=wx.ID_ANY, label=u'cm\u207b\u00b9')
        label_h_size, label_v_size = labelcm.GetTextExtent(labelcm.GetLabel())

        top_sizer = wx.FlexGridSizer(3, 2, 0, 0)
        border_in = 3

        # the nm row:
        self.edit_nm = FloatTextCtrl(self.the_panel, style=wx.TE_RIGHT, size=(8 * label_v_size, label_v_size))
        labelnm = wx.StaticText(self.the_panel, id=wx.ID_ANY, label='nm', size=(label_h_size, label_v_size))
        top_sizer.Add(self.edit_nm, 0, wx.ALL, border_in)
        top_sizer.Add(labelnm, 0, wx.ALL, border_in)

        # the cm-1 row:
        self.edit_cm = FloatTextCtrl(self.the_panel, style=wx.TE_RIGHT, size=(8 * label_v_size, label_v_size))
        top_sizer.Add(self.edit_cm, 0, wx.ALL, border_in)
        top_sizer.Add(labelcm, 0, wx.ALL, border_in)

        # the eV row:
        self.edit_ev = FloatTextCtrl(self.the_panel, style=wx.TE_RIGHT, size=(8 * label_v_size, label_v_size))
        labelev = wx.StaticText(self.the_panel, id=wx.ID_ANY, label='eV', size=(label_h_size, label_v_size))
        top_sizer.Add(self.edit_ev, 0, wx.ALL, border_in)
        top_sizer.Add(labelev, 0, wx.ALL, border_in)

        top_sizer.AddGrowableCol(0, 0)

        # set the size of the window
        self.the_panel.SetSizer(top_sizer)
        top_sizer.Fit(self)

        self.Bind(wx.EVT_CHAR_HOOK, self.on_escape)

        self.edit_nm.Bind(wx.EVT_KEY_UP, self.show_values)
        self.edit_cm.Bind(wx.EVT_KEY_UP, self.show_values)
        self.edit_ev.Bind(wx.EVT_KEY_UP, self.show_values)

        self.edit_nm.Bind(wx.EVT_TEXT, self.show_range)

    def on_escape(self, event):
        # quit application if ESC pressed
        key_code = event.GetKeyCode()
        if key_code == wx.WXK_ESCAPE:
            self.Close()
        event.Skip()

    def show_range(self, event):
        # show hint in status bar
        the_obj = event.GetEventObject()
        if len(the_obj.GetLineText(0)) > 0:
            self.status_bar.SetStatusText(nm_to_range(float(the_obj.GetLineText(0))))

    def show_values(self, event):
        # do the math and show results in other text controls
        if self.edit_nm.IsModified():
            if len(self.edit_nm.GetLineText(0)) > 0:
                self.edit_cm.SetValue(nm_to_cm(self.edit_nm.GetLineText(0)))
                self.edit_ev.SetValue(nm_to_ev(self.edit_nm.GetLineText(0)))
            self.edit_nm.SetModified(False)

        if self.edit_cm.IsModified():
            if len(self.edit_cm.GetLineText(0)) > 0:
                self.edit_nm.SetValue(cm_to_nm(self.edit_cm.GetLineText(0)))
                self.edit_ev.SetValue(cm_to_ev(self.edit_cm.GetLineText(0)))
            self.edit_cm.SetModified(False)

        if self.edit_ev.IsModified():
            if len(self.edit_ev.GetLineText(0)) > 0:
                self.edit_nm.SetValue(ev_to_nm(self.edit_ev.GetLineText(0)))
                self.edit_cm.SetValue(ev_to_cm(self.edit_ev.GetLineText(0)))
            self.edit_ev.SetModified(False)


if __name__ == "__main__":
    app = wx.App()
    frame = LcalcFrame(None, "EMcalc")
    frame.Center()
    frame.Show()
    app.MainLoop()
